config/routes.rb
Coder::Application.routes.draw do

  resources :likes

  devise_for :users, :controllers => {sessions: 'sessions'}
  resources :users, :only => [:show]

  resources :resources do
    resources :likes
    resources :reviews do
      resources :comments
    end
  end

  resources :favorite_resources, only: [:create, :destroy]

  resources :categories
  resources :subcategories

  root 'welcome#landing'

  match 'remote_sign_up', to: 'remote_devise#remote_sign_up', via: [:get]

end

app/models/like.rb
class Like < ActiveRecord::Base

  belongs_to :resource, :counter_cache => true
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user
  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create

    @resource = Resource.find(params[:resource_id])
    @like = @resource.likes.build(like_params)
    @like.user_id = current_user.id

    respond_to do |format|
      if @like.save

        format.json { render action: 'show', status: :created, location: @like }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to likes_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_like
    @like = Like.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def like_params
    params[:like]
  end


end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_form.html.erb
<%= form_for(@like) do |f| %>
  <% if @like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% @like.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/likes/_likes_count.html.erb
<i class="fa fa-thumbs-o-up fa-lg"></i><%= @resource.likes.count %>

app/views/likes/create.js.erb
$(".new_like").fadeOut();
$('.orbit-likes-index').html('<%=j(render :partial => 'resources/likes_count') %>');

app/views/likes/edit.html.erb
<h1>Editing like</h1>

<%= render 'form' %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<h1>Listing likes</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

app/views/likes/new.html.erb
<h1>New like</h1>

<%= render 'form' %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>