config/routes.rb
Coder::Application.routes.draw do

  resources :likes

  devise_for :users, :controllers => {sessions: 'sessions'}
  resources :users, :only => [:show]

  resources :resources do
    resources :likes
    resources :reviews do
      resources :comments
    end
  end

  resources :favorite_resources, only: [:create, :destroy]

  resources :categories
  resources :subcategories

  root 'welcome#landing'

  match 'remote_sign_up', to: 'remote_devise#remote_sign_up', via: [:get]

end

app/models/category.rb
class Category < ActiveRecord::Base




  has_many :subcategories
  has_many :resources, :through => :subcategories
end

app/models/comment.rb
class Comment < ActiveRecord::Base


  belongs_to :user

  belongs_to :review
  delegate :resource, :to => :review
  validates :user_id, presence: true
  validates :review_id, presence: true
  validates :content, presence: true, length: { maximum: 25000 }
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/like.rb
class Like < ActiveRecord::Base

  belongs_to :resource, :counter_cache => true
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  belongs_to :resource
  has_many :comments

  validates :user_id, presence: true

  validates :content, presence: true, length: { maximum: 25000 }
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  default_scope { order('created_at DESC') }

  scope :with_likes, order('likes_count DESC')


  has_many :likes
  has_many :favorites, :as => :favorited
  belongs_to :user
  belongs_to :subcategory
  has_many :reviews, dependent: :destroy

  #belongs_to :category, :through => :subcategory
  delegate :category, :to => :subcategory

  mount_uploader :image, ImageUploader

  # def average_rating
  #   puts "SUM #{reviews.sum(:score)}"
  #   puts "SIZE #{reviews.size}"
  #   sum = reviews.sum(:score)
  #   reviews_count = reviews.size
  #
  #   sum/reviews_count
  #
  # end

  def average_rating
    if reviews.blank?
      0
    else
      reviews.average(:score).round(2, :up).to_f
    end

  end


end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :resource
  has_many :comments

  validates :user_id, presence: true

  validates :content, presence: true, length: { maximum: 25000 }
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base

  belongs_to :category
  has_many :resources
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :resources
  has_many :favorites
  has_many :favorite_resources, through: :favorites, source: :favorited, source_type: 'Resource'
  has_many :likes, :through => :resources
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user
  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create

    @resource = Resource.find(params[:resource_id])
    @like = @resource.likes.build(like_params)
    @like.user_id = current_user.id

    respond_to do |format|
      if @like.save

        format.json { render action: 'show', status: :created, location: @like }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to likes_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_like
    @like = Like.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def like_params
    params[:like]
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:create, :edit, :update, :destroy]


  def index

  end


  def create

    @resource = Resource.find(params[:resource_id])
    @post = @resource.posts.build(post_params)
    @post.user_id = current_user.id

    # @comment = current_user.comments.build(:resource => @resource)
    respond_to do |format|
      if @post.save
        format.html { redirect_to(@resource, :notice => 'Comment was successfully created.') }
        format.xml { render :xml => @resource, :status => :created, :location => @resource }
        format.js
      else
        format.html { redirect_to(@resource, :notice =>
            'Comment could not be saved. Please fill in all fields') }
        format.xml { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:content, :resource_id, :user_id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  before_action :set_user, only: [:show]

  def show

  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_likes(current_user, resource_id)
    Like.first(:conditions => ['user_id = ? AND resource_id = ?', current_user, resource_id]).nil?
  end

def nice_time(time)
  time.strftime("%B #{time.day.ordinalize}, %Y")

end


  protected

  def current_user?(user)
    user == current_user
  end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/custom_failure.rb
class CustomFailure < Devise::FailureApp
  def redirect_url
    if warden_options[:scope] == :user
      new_user_session_path
    else
      new_user_session_path
    end
  end
  def respond
    if http_auth?
      http_auth
    else
      redirect
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper

  def medium_texter(medium)
    case medium # a_variable is the variable we want to compare
      when 1    #compare to 1
        "Book"
      when 2    #compare to 2
        "Video"
      when 3    #compare to 2
       "Blog-Tutorial"
      when 4    #compare to 2
   "Article"
      when 5    #compare to 2
        "Video-Tutorial"
      when 6    #compare to 2
        "Tutorial-Exercises"
      else
        "Unknown Type"
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ratings/update.js.erb
$('#star').raty({
    readOnly: true,
    score: <%= @resource.average_rating %>,
    path: '/assets'
});

$('#user_star').raty({
    score: <%= @rating.score %>,
    path: '/assets',
    click: function(score, evt) {
        $.ajax({
            url: '/ratings/' + <%= @rating.id %>,
            type: 'PATCH',
            data: { score: score }
        }).done(function (data){});
    }
});

app/views/remote_devise/_remote_sign_up.html.erb
<div class="modal hide fade in" id="loginModal">

  <div class="modal-header">

    <button class="close" data-dismiss="modal">x</button>

    <h2>Sign in</h2>

    <%= form_for(:user, :as => resource_name, :url => session_path(resource_name),:format => :json,:html => {:id => "sign_in_user"}) do |f| %>
      <div><%= f.label :email %><br />
        <%= f.email_field :email, :autofocus => true %></div>

      <div><%= f.label :password %><br />
        <%= f.password_field :password %></div>

      <% if devise_mapping.rememberable? -%>
        <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
      <% end -%>

      <div><%= f.submit "Sign in" %></div>

      <%= render "devise/shared/links" %>

      </div>

      <div class="modal-footer">

        <p><div><%= f.submit "Sign up", :class => 'btn btn-small btn-success' %></div></p>

        <p><a href="#" class="btn btn-small" data-dismiss="modal">Close</a></p>

      </div>

    <% end %>

    </div>

app/views/remote_devise/remote_sign_up.js.erb
if($('.modal').length > 0) {
  $("#sign_up_modal").modal();
}
else {
  $("body").prepend("<%= escape_javascript(render "remote_sign_up", :formats => [:html]) %>");
  $("#sign_up_modal").modal();
}

app/views/resources/_form.html.erb
<div class="">
  <%= form_for @resource, :html => {:multipart => true} do |f| %>
      <% if @resource.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

            <ul>
              <% @resource.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :link %>
        <%= f.text_field :link %>
      </div>
      <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description %>
      </div>
      <div class="field">

        <%= f.label :medium %>
        <%= f.select :medium, options_for_select([['Book', '1'], ['Video', '2'], ['Blog-Tutorial', '3'], ['Article', '4'], ['Video-Tutorial', '5'], ['Tutorial-Exercises', '6']]), {}, {:class => "small-3"} %>
      </div>
      <div class="field">
        <%= f.label :category_id %>
        <%= f.collection_select :category_id, Category.order(:name), :id, :name, {:prompt => "--Select a Category--"}, {:class => "small-4"} %>
      </div>
      <div class="field subcat-field">
        <%= f.label :subcategory_id %>
        <%= f.grouped_collection_select :subcategory_id, Category.order(:name), :subcategories, :name, :id, :name, {include_blank: true}, {:class => "small-3"} %>
      </div>
      <div class="field">
        <%= f.label :source %>
        <%= f.text_field :source %>
      </div>
      <div class="field">
        <%= f.label :rating %>
        <%= f.select :rating, options_for_select(1..10), {}, {:class => "small-3"} %>
      </div>

      <div>
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>
      <div class="field">
        <%= f.label :level %>
        <%= f.select :level, options_for_select(['Beginner', 'Intermediate', 'Advanced']), {}, {:class => "small-3"} %>
      </div>
      <div class="field">
        <%= f.label :year %>
        <%= f.select :year, options_for_select(2000..Time.now.year, :selected => Time.now.year), {}, {:class => "small-3"} %>
      </div>
      <div class="actions">
        <%= f.submit class: "btn btn-success" %>
      </div>
  <% end %>
</div>

app/views/resources/_latest.html.erb
<div class="well">
  <% @resources.each do |resource| %>
      <%= link_to(resource_path(resource)) do %>
          <%= resource.title %>


          <% if resource.image? %>
              <%= image_tag(resource.image_url, :class => "img-thumbnail") %>
          <% else %>
              <%= image_tag('CS.gif', :class => "img-thumbnail") %>
          <% end %>
      <% end %>
  <% end %>
</div>

app/views/resources/_likes.html.erb
<div>
  <%= form_for([@resource, @resource.likes.build], :remote => true, :id => "like-form")  do |f| %>

      <%= f.submit "Like This", class: 'button tiny success radius like-this' %>
  <% end %>
</div>

app/views/resources/_likes_count.html.erb
<i class="fa fa-thumbs-o-up fa-lg"></i><%= @resource.likes.count %>

app/views/resources/_resource.html.erb
<div class="well">
  <div class="row">
    <div class="col-md-8">
      <%= @resource.title %>
    </div>
    <div class="col-md-4">
      <%= link_to "#{@resource.category.name} / #{@resource.subcategory.name}", subcategory_path(@resource.subcategory.id) %>
    </div>

  </div>
  <div class="row">
    <div class="col-md-2">

      <% if @resource.image? %>
          <%= image_tag(@resource.image_url, :class => "img-thumbnail") %>
      <% else %>
          <%= image_tag('CS.gif', :class => "img-thumbnail") %>
      <% end %>
    </div>

    <div class="col-md-10">
      <%= @resource.description %>
    </div>

  </div>
  <div class="row">
    <div class="col-md-6">
      <%= @resource.source %>
    </div>
    <div class="col-md-6">
      <%= @resource.level %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= @resource.cost %>
    </div>
    <div class="col-md-6">
      <%= @resource.year %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= medium_texter(@resource.medium) %>
    </div>
    <div class="col-md-6">
      <%=  %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="raty-stars" data-score=<%= @resource.average_rating %>></div><small class="tiny"> (<%= @resource.reviews.count %> <%= 'Review'.pluralize(@resource.reviews.count)  %>  )</small>
    </div>
    <div class="col-md-6">
      <%= @resource.user.username %> | <%= nice_time(@resource.created_at) %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%- if current_user.favorite_resources.find_by_id(@resource.id) -%>
          <%= link_to 'Remove from favorites', favorite_resource_path(@resource), method: :delete %>
      <%- else -%>
          <%= link_to 'Add to favorites', favorite_resources_path(resource_id: @resource), method: :post %>
    <%- end -%>
    </div>
    <div class="col-md-6">
      <%= @resource.user.username %> | <%= nice_time(@resource.created_at) %>
    </div>
  </div>

</div>

app/views/resources/_resources.html.erb
<div class="well clearfix">
  <% @resources.each do |resource| %>

      <%= link_to(resource_path(resource)) do %>

          <div class="col-sm-3 col-lg-3 col-md-3">
            <div class="thumbnail list-resource">
              <div class="img-wrapper">
                <% if resource.image? %>
                    <%= image_tag(resource.image_url, :class => "img-thumbnail") %>
                <% else %>
                    <%= image_tag('CS.gif', :class => "img-thumbnail") %>
                <% end %>
              </div>
              <div class="caption">
                <h4 class="pull-right">$24.99</h4>
                <h4><a href="#"><%= resource.title %></a>
                </h4>

                <p>See more snippets like this online store item at
                  <a target="_blank" href="http://www.bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>
              </div>
              <div class="ratings">
                <p class="pull-right">15 reviews</p>

                <p>
                  <span class="glyphicon glyphicon-star"></span>
                  <span class="glyphicon glyphicon-star"></span>
                  <span class="glyphicon glyphicon-star"></span>
                  <span class="glyphicon glyphicon-star"></span>
                  <span class="glyphicon glyphicon-star"></span>
                </p>
              </div>
            </div>
          </div>


      <% end %>

  <% end %>

</div>

app/views/resources/_reviews.html.erb
<h4>Reviews</h4>

<% if @resource.reviews.blank? %>
    <div class="well text-center">
      <h3>No reviews just yet, would you like to add the first!</h3>
    </div>
<% else %>
    <%= render :partial => @resource.reviews %>
<% end %>
<%= form_for([@resource, @resource.reviews.build]) do |f| %>
    <div>
      <%= f.label 'Review This Resource' %>
      <%= f.text_area :content, :cols => 20, :rows => 2, :id => 'comment-txt' %>

      <div id="star-rating"></div>
    </div>
    <p><%= f.submit "Add Review", class: 'btn btn-success' %></p>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<div class="container">

  <div class="row">

    <div class="col-md-2">
      <%= render 'layouts/sidenav' %>
    </div>
    <div class="col-md-10">
      <%= render 'resources/resources' %>
    </div>


  </div>
</div>

app/views/resources/new.html.erb
<div class="container">
  <div class="row">
    <h1>New resource</h1>

    <%= render 'form' %>

    <%= link_to 'Back', resources_path %>
  </div>
</div>

app/views/resources/show.html.erb
<%= javascript_include_tag 'side_nav.js.erb' %>
<div class="container">

  <div class="row">

    <div class="col-md-2">
      <%= render 'layouts/sidenav' %>
    </div>
    <div class="col-md-8">
      <div class="row">
      <%= render 'resources/resource' %>
      </div>
      <div class="row">
        <%= render 'resources/reviews' %>
      </div>

    </div>

    <div class="col-md-2">
      <%= render 'resources/latest' %>
    </div>


  </div>
</div>

app/views/resources/show.js.erb
$(function() {
  var subCat = '<%= j resource_subcat_id %>';
  var test = subCat;
  console.log(subCat);
});

console.log('test');