config/routes.rb
Coder::Application.routes.draw do

  resources :likes

  devise_for :users, :controllers => {sessions: 'sessions'}
  resources :users, :only => [:show]

  resources :resources do
    resources :likes
    resources :reviews do
      resources :comments
    end
  end

  resources :favorite_resources, only: [:create, :destroy]

  resources :categories
  resources :subcategories

  root 'welcome#landing'

  match 'remote_sign_up', to: 'remote_devise#remote_sign_up', via: [:get]

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:create, :edit, :update, :destroy]


  def index

  end


  def create

    @resource = Resource.find(params[:resource_id])
    @review = @resource.reviews.build(review_params)
    @review.user_id = current_user.id

    # @comment = current_user.comments.build(:resource => @resource)
    respond_to do |format|
      if @review.save
        format.html { redirect_to(@resource, :notice => 'Review was successfully created.') }
        format.xml { render :xml => @resource, :status => :created, :location => @resource }
        format.js
      else
        format.html { redirect_to(@resource, :notice =>
            'Review could not be saved. Please fill in all fields') }
        format.xml { render :xml => @review.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @resource = Resource.find(params[:resource_id])
    @review.destroy
    redirect_to(@resource, :notice => 'Review was successfully deleted.')
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def review_params
    params.require(:review).permit(:content, :score, :resource_id, :user_id)
  end


end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_review.html.erb
<div id="comment<%= (review.id) %>" class="well">
  <div class="post-container">
    <div class="row">
      <div class="col-lg-2">
        <div class="comment-img">

          <%= image_tag('default-user.jpg', :class => "img-thumbnail") %>


        </div>

      </div>

      <div class="col-lg-10">
        <div class="post-content">
          <%= review.content %>
          <div class="commentname"><b><%= review.user.username %></b>
            <small class="tiny"> (<%= time_ago_in_words(review.created_at) %> ago)</small>
          </div>
          <div class="score">
            <div class="raty-stars" data-score=<%= review.score %>>
            </div>

            <% if current_user?(review.user) %>
                <%= link_to 'Delete', resource_review_path(@resource, review), :class => 'btn btn-sml btn-warning', :confirm => 'Are you sure?', :method => :delete %>
            <% end %>
          </div>
        </div>
      </div>
    </div>


    <div class="reply-container col-lg-offset-2">
      <% unless review.comments.empty? %>
          <%= render review.comments %>
      <% end %>

      <% if review %>
          <%= form_for([@resource, review, review.comments.build], id: "posts") do |f| %>
              <div>
                <%= f.label 'Add a Reply' %>
                <%= f.text_area :content, :cols => 20, :rows => 2, :id => 'commtxt' %>
              </div>

              <p><%= f.submit "Reply", class: 'btn btn-info' %></p>
          <% end %>

      <% end %>

    </div>
  </div>
</div>